### ISSUE TITLE
Re: Application licensing issues and contribution guideline violation

### ISSUE THREAD

**Issue by Nitepone** [flipperdevices/flipper-application-catalog#193]
So, I got pinged on #192, but didn't have a chance to respond on it before it was closed..

First, I want to stress that **I am happy with my code being included here**. As it was a small thing **I threw together for fun and without intent to profit**.

However, @xMasterX in #30 indicated that they "I own the code I'm submitting or have code owner's permission to submit it". This is sadly completely untrue. At no point was I contacted about my app being added to this repo. In fact, I found out about this repo from seeing my app being distributed on the flipper catalogue. And it seems it was added here before the catalogue was publicly available for use? 

It makes me slightly uneasy that @xMasterX uses the intervalometer flipper page on the catalogue to link back to their Github account where they request donations. Especially since I gave no consent for my code to be added here. Nor does it have any license to provide permission to do so!

If not a legal issue, it looks to be a violation of your contribution guidelines since the assertion of ownership in #30 is false.

That all said, I really don't care what you do here. But it was a bit disappointing for me to see that my project was uploaded to this catalogue by someone else without my consent and without even linking to my original repo. While I am happy to share my code with the community, I wish there was some engagement before it was included here.

**Comment by skotopes** [comment]
There are 2 options:
- We can remove app from catalog entirely 
- You can submit PR to this repo with new app manifest that will reference your repository

**Comment by xMasterX** [comment]
> It makes me slightly uneasy that @xMasterX uses the intervalometer flipper page on the catalogue to link back to their Github account where they request donations. 

Can you show me where I request donations in the apps repo?
Can you show me where I did not added link to original repo? Or not mentioned original authors?
Can you explain what "profit" you are talking about?

App catalogue works in a way that it links to the repo where app was published, I'm maintaining that repo, fixing abandoned apps and keeping someones work alive
However even when some plugins was completely or in half rewritten by me, I still include links, usernames, of original authors
Only if app was completely remade from scratch, then I will say only name of person who did this "new version" 

There is no way to ask 100s of authors of they want their plugins be published here or not
They always have option to request removal from catalouge, or my repo, I will accept that request even if that against GPLv3 which all plugins without license are licensed under GPLv3 as they was made inside of flipper's firmware using its SDK and cannot work independently, even can't compile without flipper's firmware
Due to license I can distribute code made for/with flipper's firmware without asking

If you are not happy with your app being published/updated/maintained here by me, follow any of two options that @skotopes suggested

**Comment by Nitepone** [comment]
I'll submit a PR to update the app manifest tomorrow. But that isn't a big deal to me.

However, given the ownership/permission requirement the submission guidelines on this repo. I would suggest that permission is gathered in written form (such thru notification and comment in the PR) before a project manifest from a non-codeowner is accepted.

Secondly, and more importantly licenses for each app need to be supplied in the manifest at PR time. Licenses also need to be followed properly or the submission guidelines should limit what licenses are allowed.

For example:

- "Protoview", was added to this app catalogue and is distributed as a binary through the Flipper iOS app. However, the mobile apps do not provide the full BSD license text as legally required by the BSD license. https://github.com/antirez/protoview/blob/main/LICENSE

- My own app, was accepted here and distributed as a binary without any license.

While these license violations are relatively minor; they could be an issue with the App Store and Play Store.

The submission process of this repo should consider and track licenses to avoid any issues with this.

If all applications are expected to be GPLv3 to comply with building against the flipper SDK's license, then projects supplying erroneous licenses like BSD should not be accepted.

**Comment by Nitepone** [comment]
> Can you show me where I request donations in the apps repo?

As I mentioned, these donation options were on your Github account page, which owns the "all-the-plugins" repo.

> If you are not happy with your app being published/updated/maintained here by me

I have no issue with you providing/maintaining a fork of my code. I just wish I was notified as the contribution guidelines here require.

> I'm maintaining that repo, fixing abandoned apps and keeping someones work alive

I greatly appreciate this! And am glad that you do this. Projects like my intervalometer app are something that I am happy to have picked up and maintained by others since they are likely to become abandoned. The concern I am trying to raise here is with the submission process to this repo, and not with your work. I apologise if I have accidentally caused any offense as it was not my intent.

**Comment by skotopes** [comment]
Protoview license can be seen in the repo itself, link to the repo provided in app catalog itself. There is no violation.
As for your app: I've removed it from catalog.
